version: "3"
services:
  microservices_app:
    depends_on:
      - mongo
    image: 30300101/app-image-manager
    container_name: app-micro
    restart: always
    environment:
      - DB_URL=mongodb://mongo:27017/image-db
      - RABBITMQ_HOST=rabbitmq

    links:
      - "mongo"
      - "rabbitmq"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  microservice_client:
    depends_on:
    - "rabbitmq"
    image: 30300101/client-image-manager
    container_name: client-micro
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
    - "rabbitmq"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  mongodata:
