version: "3"
services:
  microservices_app:
    depends_on:
      - db
    restart: always
    image: 30300101/app-image-manager
    environment:
      - DB_URL=mongodb://db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  microservice_client:
    depends_on:
      - db
    image: 30300101/client-image-manager
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3.6.6-management"
    container_name: rabbit_mq

    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "35197:35197"
    volumes:
      - ./conf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./data:/var/lib/rabbitmq
      - ./data/logs:/var/log/rabbitmq

volumes:
  mongodata:
